export const ADD_POSTS = "ADD_POSTS";
export const SET_POSTS = "SET_POSTS";
export const CLEAR_POSTS = "CLEAR_POSTS";
export const SET_LAST_VISIBLE = "SET_LAST_VISIBLE";
export const CLEAR_LAST_VISIBLE = "CLEAR_LAST_VISIBLE";
export const POSTS_LOADING_START = "POSTS_LOADING_START"
export const POSTS_LOADING_STOP = "POSTS_LOADING_STOP"